name: Packer and Terraform Workflow

on:
  push:

permissions:
  id-token: write

env:
  PRODUCT_VERSION: "1.10.0"

jobs:
  packer:
    runs-on: ubuntu-latest
    name: Run Packer
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: arn:aws:iam::874599947932:role/gitaws
          role-session-name: github-actions
          aws-region: us-east-1  

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        with:
          packer_version: "1.10.0"
          
      - name: Run `packer init`
        id: init
        run: "packer init ./jenkinsubuntu.pkr.hcl"

      - name: Run `packer validate`
        id: validate
        run: "packer validate ./jenkinsubuntu.pkr.hcl"

      - name: Run `packer build`
        id: build
        run: packer build -machine-readable ./jenkinsubuntu.pkr.hcl | tee build.log

      - name: Show Build Log
        run: cat build.log

      - name: Extract AMI ID
        id: extract-ami
        run: |
          AMI_ID=$(grep 'artifact,0,id' build.log | cut -d, -f6 | cut -d: -f2)
          echo "::set-output name=ami_id::$AMI_ID"


  terraform:
    runs-on: ubuntu-latest
    needs: packer
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.1.7"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: arn:aws:iam::874599947932:role/gitaws
          role-session-name: github-actions
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve -var="source_ami_id=${{ steps.packer.outputs.ami_id }}"
