name: Packer and Terraform Workflow

on:
  push:

permissions:
  id-token: write # This is required for requesting the JWT

env:
  PRODUCT_VERSION: "1.10.0" # or: "latest"

jobs:
  packer:
    runs-on: ubuntu-latest
    name: Run Packer
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: arn:aws:iam::874599947932:role/gitaws
          role-session-name: github-actions
          aws-region: us-east-1  

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        with:
          packer_version: "1.10.0"
          

      - name: Run `packer init`
        id: init
        run: "packer init ./jenkinsubuntu.pkr.hcl"

      - name: Run `packer validate`
        id: validate
        run: "packer validate ./jenkinsubuntu.pkr.hcl"

      - name: Run `packer build`
        id: build
        run: packer build -machine-readable ./jenkinsubuntu.pkr.hcl | tee build.log

      - name: Extract AMI ID
        id: extract-ami
        run: |
          AMI_ID=$(grep 'artifact,0,id' build.log | cut -d, -f6 | cut -d: -f2)
          echo "AMI_ID=$AMI_ID" >> $GITHUB_ENV
        shell: bash

  terraform:
    runs-on: ubuntu-latest
    needs: packer
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: arn:aws:iam::874599947932:role/gitaws
          role-session-name: github-actions
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve -var "source_ami_id=${{ env.AMI_ID }}"

      - name: Debugging
        run: |
          echo "Before grep command"
          grep 'artifact,0,id' build.log | cut -d, -f6 | cut -d: -f2
          echo "After grep command"
  
